#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
prompt agnoster
export EDITOR=`echo =vim`
bindkey -v

function pyc(){
    rm -f **/*.pyc
    rm -rf **/__pycache__
}

. ~/.dotfiles/z/z.sh
. ~/.zshrc_local

alias dcp=docker-compose
alias dk=docker
alias dmc=docker-machine
alias g=git
alias v=vim
